docs/reference/js-client.md
* Clear the container on unmount. This prevents the container from being
populated multiple times on hotreload.
* Include a dependency array in `useEffect` initialization to make sure
it only runs when it needs to.
=> update react example

docs/reference/android_sdk.md
**This PR Addresses:**  
[Android Push SDK Docs](https://trello.com/c/ZwX8ruxM/1267-android-push-sdk-docs)  
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> Android reference docs

assets/files/notificationapi-service-worker.js
**This PR Addresses:**  
[Service worker file in S3 or GitHub](https://trello.com/c/QwDK9npw/1346-service-worker-file-in-s3-or-github)  
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> add coments to the ServiceWorker file

docs/guides/web_push.md
**This PR Addresses:**  
[fix Service Worker](https://trello.com/c/DuYA9TnE/1364-fix-service-worker)  
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> fix Service Worker

docs/reference/js-client.md, static/custom.js, yarn.lock
**This PR Addresses:**  
[Add Angular example](https://trello.com/c/uaI9VZdJ/1391-add-angular-example)  
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> Add Angular Example

docs/reference/server.md
- Allow the new delivery in postPref
=> - Allow empty postPref

docusaurus.config.js, src/css/custom.css
Move search to center and custom style
=> Adjust search

docs/quick-start/display-inapp-notifications.md, docs/quick-start/send-a-notification.md, docs/reference/js-client.md, docs/reference/js-core.md, docs/reference/react-sdk.md, docs/reference/server.md
Allow users the ability to use the copy and not copy all commands together and added the new sound prop to the notificationapiprovider
=> Adjustment

docs/reference/react-sdk.md
=> added identify, modified provider

docs/reference/js-client.md
=> Added service worker setup for each framework

package-lock.json, package.json
Include the `path-to-regexp` dependency in the project and adjust the start script in `package.json` for consistency.
=> Add path-to-regexp dependency and update start script

package-lock.json, package.json
Restore the original format of the start script and remove an unused dependency from package.json.
=> Return changes to package.json scripts and dependencies

package-lock.json, package.json
Update the @notificationapi/react dependency to the latest version for improved functionality and performance.
=> update path-to-regexp dependency to version 3.3.0

docs/channels/inapp.md, docs/faq.md
=> Update docs keywords for Jan 27th Feb 3rd and add FAQ

docs/reference/react-sdk.md
To be merged after react sdk pr.
https://github.com/notificationapi-com/notificationapi-react-client-sdk/pull/35
=> Add documentation for customizing notification regions in React SDK

docs/quick-start/send-a-notification.md, docs/reference/server.md
Update quickstart to use actual C# package with send example and bump to version 0.5.0 to match NuGet.
=> Update C# SDK documentation for the quickstart guide

docs/quick-start/send-a-notification.md
Update the quick start guide for python to match the server ref guide
=> Update quick start

docs/reference/server.md
Update the server doc to include updated information with the new values available for specific region use for customers.
=> Update server documentation

docs/reference/server.md
Update Laravel Server SDK documentation with region compatibility and updated installation instructions
- Added compatibility note for Laravel versions 9, 10, and 11
- Clarified installation steps for the Laravel Server SDK
- Updated service provider registration instructions for Laravel 11
- Included optional region configuration for notifications
- Add samples for setting the region with .env variables
- Update parameters descriptions
- Add NotificationUser class code snippet
- Improved example code for sending notifications with merge tags
=> Update go code sample to support all regions

docs/reference/server.md
- Add `secureMode` option and clarified usage of `baseURL` for different regions.
- Update code samples for creating `NotificationUser` and sending notifications with region constants.
](url)
=> Update C# server documentation to include region instructions

docs/intro.md, docs/quick-start/send-a-notification.md, docs/reference/server.md
- Added Java as a supported environment in intro.md\n- Added Java SDK installation instructions to quick-start guide
- Added comprehensive Java SDK documentation to server reference
This PR adds full documentation for the new Java SDK (version 0.1.0)
=> docs(sdk): Add Java SDK documentation

docs/channels/slack.md, package-lock.json, package.json
- Added comprehensive Slack integration documentation
- Requirements and prerequisites
- Detailed setup instructions with app manifest
- OAuth scope configuration
- Security best practices
- Message formatting examples with Block Kit
- User identification methods
- Channel message handling
- Tracking options and best practices
- Added react-icons dependency for Slack icon support
The documentation provides a complete guide for setting up and using the Slack integration, including troubleshooting tips and security considerations. The addition of react-icons enables consistent icon usage throughout the documentation.
=> docs(slack): add comprehensive Slack integration documentation

docs/channels/slack.md
- Updated the Slack integration guide to provide a clearer overview and detailed requirements for connecting NotificationAPI with Slack.
- Added a frontend integration example for various frameworks, including React, Next.js, Remix, Angular, and Vue, to facilitate user account connections.
- Improved organization of content and clarified setup instructions, ensuring users can easily follow the integration process.
These changes aim to streamline the integration experience and enhance user understanding of Slack notifications with NotificationAPI.
=> Enhance Slack integration documentation
